name: umccrise

channels:
  - vladsaveliev
  - pdiakumis
  - bioconda
  - conda-forge
  - defaults

dependencies:
  - python>=3.6
  - cython
  - bcftools>=1.9
  - bedtools
  - samtools
  - vcfanno
  - vcflib  # for VCF normalisation
  - pythonpy
  - click
  - cyvcf2>=0.10.0
  - numpy>=1.15.0
  - pandas
  - curl>=7.59  # to make sure libcurl.4.dylib>=10.0.0 is installed
  - snakemake-minimal
  - nose
  - pip:
    - "--editable=git+https://github.com/umccr/hpc_utils#egg=hpc_utils"
    - "--editable=git+https://github.com/umccr/vcf_stuff#egg=vcf_stuff"
    - "--editable=git+https://github.com/vladsaveliev/NGS_Utils#egg=ngs_utils"
  #
  # Umccrise-specific
  - natsort  # for bcbio.py in ngs_utils
  # - pybedtools  # for ref data generation
  # - sambamba  # for test data generation
  # - tabix     # for test data generation
  - goleft
  - awscli
  - pyasn1 # for awscli - for some reason doesn't install automatically on macos
  - parallel
  - cnvkit
  - multiqc
  - networkx   # for snakemake report
  - pygraphviz # for snakemake report
  # R libraries
  - pandoc<2  # r-rmarkdown 1.6 doesn't support pandoc 2, and a more recent r-rmarkdown is not available on conda
  - r
  - r-rmarkdown
  - r-ggplot2
  - r-tidyr
  - r-dt
  - r-stringi>=1.1.7  # for pcgrr
  - bioconductor-delayedarray
  - bioconductor-summarizedexperiment>=1.8
  - bioconductor-mutationalpatterns
  - bioconductor-bsgenome.hsapiens.ucsc.hg19
  - bioconductor-txdb.hsapiens.ucsc.hg19.knowngene
  - bioconductor-bsgenome.hsapiens.ucsc.hg38
  - bioconductor-txdb.hsapiens.ucsc.hg38.knowngene
  - bioconductor-genomeinfodb
  - bioconductor-genomeinfodbdata
  - bioconductor-omiccircos  # for Peter's circos rock
  - libgfortran-ng
  - r-rock                 # from pdiakumis channel
  - r-kableextra                 # from pdiakumis channel
  - r-vcfr
  - r-devtools
  - r-readr
  - r-stringr
  - r-htmlwidgets>=1.0  # dependency requirement for DT (by default, 0.9 is getting installed)
  - circos=0.69.6         # for circos
  - libgd=2.2.5           # for circos
  - perl=5.22.0           # for circos
